image: python:3.8-bullseye

before_script:
  - pip install mkdocs mkdocs-material

pages:
  stage: deploy
  script:
    - git push 
    - mkdocs build --strict --verbose
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
